#!/bin/sh

amixer set Master $1

status=$(amixer get Master | tail -n 1 | cut -d '[' -f 3 | cut -d ']' -f 1 | sed s/o/O/)
vol=$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | cut -d ']' -f 1)

echo "$vol"
echo "$status"

if [ "$status" == "Off" ]
then
    notify-send "Volume" "" -h int:value:0 -u low
else

    notify-send "Volume" "" -h int:value:"$vol" -u low
fi
