#!bin/zsh

export FZF_DEFAULT_OPTS="--height 40%"
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules,vendor}/*" 2> /dev/null'

# Search directory
fzd() {
  local dir
  dir=$(find ${1:-.} \
          -path '*/\.*' -prune \
          -path '*/node_modules/*' -prune \
          -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}
zle -N fzd
bindkey '^P' fzd

# Search directory history
fzh() {
  local n
  n=$(dirs -v | fzf +m | cut -f 1) && eval " cd +0$n"
}

# Search recently used commands
fzc() {
  local cmd
  cmd=$(fc -l -n 1 | sort | uniq | fzf +m) && eval "$cmd"
}

