#! /bin/sh

bspc monitor eDP-1 -d 1 2 3 4
bspc monitor HDMI-1 -d 5 6 7 8

# Borders
bspc config border_width	2
bspc config normal_border_color "#2E3440"
bspc config focused_border_color "#5E81AC"

# Layout
bspc config -m eDP-1 window_gap          30
bspc config -m eDP-1 top_padding         -12
bspc config -m eDP-1 bottom_padding      -12
bspc config -m eDP-1 right_padding       -12
bspc config -m eDP-1 left_padding        -12

bspc config -m HDMI-1 window_gap          40
bspc config -m HDMI-1 top_padding         16
bspc config -m HDMI-1 bottom_padding      -12
bspc config -m HDMI-1 right_padding       -12
bspc config -m HDMI-1 left_padding        -12

bspc config split_ratio          0.5
bspc config initial_polarity    second_child

bspc config focus_follows_pointer true

# Single window desktops
bspc config borderless_monocle	    true
bspc config gapless_monocle	        false
bspc config single_monocle	        true

# Mouse
bspc config click_to_focus		    button1
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side

# Rules
bspc rule --add Termite:htop state=floating rectangle=620x170+1260+40
bspc rule --add Chromium state=floating
bspc rule --add Zathura state=tiled
