#! /bin/sh

bspc monitor -d 1 2 3 4 5 6

# Borders
bspc config border_width	2
bspc config normal_border_color "#2E3440"
bspc config focused_border_color "#5E81AC"

# Layout
bspc config window_gap          30
bspc config top_padding         -12
bspc config bottom_padding      -12
bspc config right_padding       -12
bspc config left_padding        -12

bspc config split_ratio          0.5
bspc config initial_polarity    second_child

# Single window desktops
bspc config borderless_monocle	    true
bspc config gapless_monocle	        false
bspc config paddingless_monocle	    false
bspc config single_monocle	        true

# Mouse
bspc config click_to_focus		    true
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side

# Rules
bspc rule --add Termite:htop state=floating rectangle=620x170+1260+40

